### ISSUE TITLE
Propósito do intervalo de espera entre requisões

### ISSUE THREAD

**Issue by Marlysson** [mrmorais/uber-map-natal#1]
Olá, muito interessante o trabalho feito nesse projeto, estava analisando ele e surgiu uma dúvida.

Por qual motivo é feito um cálculo do tempo a cada requisição feita? 
Por que não deixar os tempos fixos entre as requests.. há algo de diferente que pode afetá-las?

Aqui está o trecho:

https://github.com/mrmorais/uber-map-natal/blob/master/src/uber_map.py#L43-L46

**Comment by mrmorais** [comment]
Olá, obrigado pelo interesse.

Eu fiz isso para considerar o tempo que é levado para fazer todas as requisições e garantir que cada leva de requisições é feita exatamente após 3 minutos. Se, por exemplo, levou 1 minuto para fazer as requisições o script deve esperar 2 minutos para a próxima leva, e não 3.

Não há nenhum motivo realmente crítico para fazer isso, apenas o fiz para manter o intervalo realmente constante, independente do tempo para realizar requisições. Isso pode ser um problema se as requisições tomarem mais que 3 minutos para serem feitas, realmente não cobri este caso.

**Comment by Marlysson** [comment]
Ahhh , boa estratégia. Esclareceu minha dúvida  

Muto obrigado.
